env:
  browser: true
  es2021: true
  node: true
extends:
  - standard-with-typescript
  - eslint-config-prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  createDefaultProgram: true
  project:
    - ./tsconfig.app.json
    - ./tsconfig.config.json
    - ./tsconfig.vitest.json
rules:
  '@typescript-eslint/ban-ts-comment': off
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
  import/resolver:
    typescript: {}
    alias:
      map:
        - ['@', './src']
      extensions:
        - .js
        - .ts
        - .jsx
        - .tsx
  vite:
    configPath: ./vite.config.ts
