allowBuilds:
  unrs-resolver: true
overrides:
  'eslint-plugin-import>minimatch': 3.1.4
  'minimatch@3.1.4>brace-expansion': 1.1.13
  'eslint-plugin-import-x>minimatch': 9.0.7
  'eslint-plugin-json-schema-validator>minimatch': 10.2.5
  'eslint-plugin-json-schema-validator>ajv': 8.18.0
  'json-schema-migrate-x>ajv': 8.18.0
  'ajv>fast-uri': 3.1.2
  'flat-cache>flatted': 3.4.2
  'tinyglobby>picomatch': 4.0.4
  'fdir>picomatch': 4.0.4
  '@rollup/pluginutils>picomatch': 4.0.4
  'unplugin>picomatch': 4.0.4
  'vitest>picomatch': 4.0.4
  'npm-run-all2>picomatch': 4.0.4
  'yaml-eslint-parser>yaml': 2.9.0
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
