import type MetaInterface from './interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '0.0.1',
  date: '2022-07-13T23:49:49.342Z',
};
export default meta;
